"""initial

Revision ID: 3b017149e2cf
Revises: 
Create Date: 2022-12-03 10:42:00.604416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b017149e2cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Boolean(), nullable=True),
    sa.Column('causes', sa.Boolean(), nullable=True),
    sa.Column('area', sa.Boolean(), nullable=True),
    sa.Column('time', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
